-- MySQL Script generated by MySQL Workbench
-- Sun Aug 14 18:11:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`heartseed_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`heartseed_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`heartseed_user` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` SMALLINT(15) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `interests` MEDIUMTEXT NOT NULL,
  `photo` BLOB NULL,
  `occupation` VARCHAR(45) NULL,
  `bio` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`heartseed_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`heartseed_post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`heartseed_post` (
  `id_post` INT NOT NULL,
  `posting_date` DATE NOT NULL,
  `event_date` DATE NOT NULL,
  `event_beginning_hour` TIME NOT NULL,
  `event_ending_hour` TIME NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `kind` VARCHAR(45) NOT NULL,
  `interests` MEDIUMTEXT NOT NULL,
  `title` VARCHAR(90) NOT NULL,
  `content` TEXT NOT NULL,
  `picture` BLOB NULL,
  `likes` INT NULL,
  `sponsor` VARCHAR(45) NULL,
  `heartseed_user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_post`, `heartseed_user_id_user`),
  INDEX `fk_heartseed_post_heartseed_user_idx` (`heartseed_user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_heartseed_post_heartseed_user`
    FOREIGN KEY (`heartseed_user_id_user`)
    REFERENCES `mydb`.`heartseed_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`heartseed_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`heartseed_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`heartseed_comment` (
  `id_comment` INT NOT NULL,
  `comment_posting_date` DATE NOT NULL,
  `comment_posting_hour` TIME NOT NULL,
  `content` LONGTEXT NOT NULL,
  `likes` INT NULL,
  `heartseed_post_id_post` INT NOT NULL,
  `heartseed_user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_comment`, `heartseed_post_id_post`, `heartseed_user_id_user`),
  INDEX `fk_heartseed_comment_heartseed_post1_idx` (`heartseed_post_id_post` ASC) VISIBLE,
  INDEX `fk_heartseed_comment_heartseed_user1_idx` (`heartseed_user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_heartseed_comment_heartseed_post1`
    FOREIGN KEY (`heartseed_post_id_post`)
    REFERENCES `mydb`.`heartseed_post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_heartseed_comment_heartseed_user1`
    FOREIGN KEY (`heartseed_user_id_user`)
    REFERENCES `mydb`.`heartseed_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
